version: '3'

services:
        frontend:
                container_name: 'appclientadminfront'
                image: 'danrojas7/appclientadminfront:1.0.0'
                build:
                        context: .
                        args:
                                - TZ=America/Bogota
                restart: 'always'
                ports:
                        - '8080:8080'
                links:
                        - 'backend'
                environment:
                        - TZ=America/Bogota
        backend:
                container_name: 'wsrestclientadmin'
                image: 'danrojas7/wsrestclientadmin:0.0.1'
                build:
                        context: ../WsRestClientAdmin/
                        args:
                                - TZ=America/Bogota
                                - JAR=WsRestClientAdmin-0.0.1-SNAPSHOT.jar
                                - CONFIG_PATH=src/main/resources/application.properties
                restart: 'always'
                ports:
                        - '8081:8081'
                links:
                        - 'mongo'
                environment:
                        - TZ=America/Bogota
        mongo:
                container_name: 'mongodb'
                image: 'bitnami/mongodb'
                restart: 'always'
                environment:
                        - MONGODB_DATABASE=alianza
                        - MONGODB_ROOT_PASSWORD=test
                        - MONGODB_USERNAME=alianza
                        - MONGODB_PASSWORD=alianza123
                volumes:
                        - mongodb-data:/bitnami
        mongo-express:
                container_name: 'mongo-express'
                image: 'mongo-express'
                restart: 'always'
                ports:
                        - '8082:8081'
                links:
                        - 'mongo'
                environment:
                        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
                        - ME_CONFIG_MONGODB_ADMINPASSWORD=test
volumes:
        mongodb-data:
